OOTTracker/Models/InventoryEquipmentCategories/InventoryEquipmentCategoriesEditViewModel.cs
namespace OOTTracker.Models.InventoryEquipmentCategories
{
    public class InventoryEquipmentCategoriesEditViewModel
    {
        public string? Name { get; set; }
    }
}

OOTTracker/Models/InventoryEquipmentCategories/InventoryEquipmentCategoriesFormDataModel.cs
namespace OOTTracker.Models.InventoryEquipmentCategories
{
    public class InventoryEquipmentCategoriesFormDataModel
    {
        public string? Name { get; set; }
    }
}

OOTTracker/Models/InventoryEquipmentCategories/InventoryEquipmentCategoriesIndexDto.cs
namespace OOTTracker.Models.InventoryEquipmentCategories
{
    public class InventoryEquipmentCategoriesIndexDto
    {
        public Guid Id { get; set; }
        public string? Name { get; set; }
    }
}

OOTTracker/Models/InventoryEquipmentCategories/InventoryEquipmentCategoriesIndexModel.cs
namespace OOTTracker.Models.InventoryEquipmentCategories
{
    public class InventoryEquipmentCategoriesIndexModel
    {
        public List<InventoryEquipmentCategoriesIndexDto>? Categories { get; set; }
    }
}

OOTTracker/Models/InventoryEquipmentCategories/SimpleItemDto.cs
namespace OOTTracker.Models.InventoryEquipmentCategories
{
    public class SimpleItemDto
    {
        public Guid Id { get; set; }
        public string? Name { get; set; }
    }
}

OOTTracker/Controllers/InventoryEquipmentCategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OOTTracker.Data;
using OOTTracker.Models.InventoryEquipmentCategories;

namespace OOTTracker.Controllers
{
    public class InventoryEquipmentCategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public InventoryEquipmentCategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var _categories = await _context.InventoryEquipmentCategories
                .ToListAsync();

            var _categoryDtos = _categories.Select(c => new InventoryEquipmentCategoriesIndexDto()
            {
                Id = c.InventoryEquipmentCategoryId,
                Name = c.Name,
            })
            .OrderBy(c => c.Name)
            .ToList();

            var _model = new InventoryEquipmentCategoriesIndexModel()
            {
                Categories = _categoryDtos
            };

            return View(_model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit([FromRoute] Guid? id)
        {
            InventoryEquipmentCategoriesEditViewModel _model;
            if (id == null)
            {
                _model = new InventoryEquipmentCategoriesEditViewModel();
                return View(_model);
            }

            var _category = await _context.InventoryEquipmentCategories
                .Include(c => c.InventoryEquipmentItems)
                .FirstOrDefaultAsync(c => c.InventoryEquipmentCategoryId == id);

            if (_category == null)
                return NotFound();

            _model = new InventoryEquipmentCategoriesEditViewModel()
            {
                Name = _category.Name,
                Items = _category.InventoryEquipmentItems?
                    .Select(i => new SimpleItemDto() { Id = i.InventoryEquipmentId, Name = i.Name})
                    .OrderBy(i => i.Name)
                    .ToList()
            };

            return View(_model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromRoute] Guid? id, [FromForm] InventoryEquipmentCategoriesFormDataModel model)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            InventoryEquipmentCategory? _category;

            if (id == null)
            {
                _category = new InventoryEquipmentCategory();
                await _context.InventoryEquipmentCategories.AddAsync(_category);
            }
            else
            {
                _category = await _context.InventoryEquipmentCategories
                    .FirstOrDefaultAsync(i => i.InventoryEquipmentCategoryId == id);

                if (_category == null)
                    return NotFound();
            }

            _category.Name = model.Name;
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete([FromRoute] Guid id)
        {
            var _category = await _context.InventoryEquipmentCategories
                .FirstOrDefaultAsync(i => i.InventoryEquipmentCategoryId == id);

            if (_category == null) 
                return NotFound();

            _context.InventoryEquipmentCategories.Remove(_category);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [Route("DeleteItem/{itemId}/{categoryId}")]
        public async Task<IActionResult> DeleteItem([FromRoute] Guid itemId, [FromRoute] Guid categoryId)
        {
            var _item = await _context.InventoryEquipment
                .FirstOrDefaultAsync(i => i.InventoryEquipmentId == itemId);

            if (_item == null)
                return NotFound();

            _item.InventoryEquipmentCategoryId = null;
            await _context.SaveChangesAsync();

            return RedirectToAction("Edit", new {id = categoryId});
        }
    }
}

OOTTracker/Views/InventoryEquipmentCategories/Edit.cshtml
@model OOTTracker.Models.InventoryEquipmentCategories.InventoryEquipmentCategoriesEditViewModel
@{
    Layout = "_Layout";
}

<div class="header">
    <h1 class="h4">Edit Category</h1>
</div>
<ul class="nav nav-tabs" id="categoryTabs" role="tablist">
    <li class="nav-item" role="presentation">
        <button 
            class="nav-link active" 
            id="category-tab" 
            data-bs-toggle="tab" 
            data-bs-target="#category" 
            type="button" 
            role="tab" 
            aria-selected="true">Category
        </button>
    </li>
    <li class="nav-item" role="presentation">
        <button 
            class="nav-link" 
            id="items-tab" 
            data-bs-toggle="tab" 
            data-bs-target="#items"
            type="button"
            role="tab"
            aria-selected="true">Items
        </button>
    </li>
</ul>
<div class="tab-content mt-3">
    <div id="category" class="tab-pane fade show active" role="tabpanel" aria-labelledby="category-tab">
        <form method="post">
            <div class="row mb-3">
                <div class="col-md-6">
                    <label asp-for="Name">Category Name</label>
                    <input asp-for="Name" class="form-control" />
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="d-flex justify-content-between">
                        <button type="submit" class="btn btn-primary me-2">Save Changes</button>
                        <a asp-action="Index" class="btn btn-secondary">Cancel</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div id="items" class="tab-pane fade">
        <div class="table-responsive">
            <table 
                data-toggle="table" 
                data-pagination="true" 
                data-page-size="10" 
                data-search="true" 
                class="table table-striped table-hover">
                <thead class="table-dark">
                    <tr>
                        <th data-width="125" scope="col">#</th>
                        <th data-field="Name" data-sortable="true">Item</th>
                        <th data-width="200" scope="col">Actions</th>
                    </tr>
                </thead>
                @if (Model.Items != null)
                {
                    var categoryId = ViewContext.RouteData.Values["id"];
                    <tbody>
                        @for (var i = 0; i < Model.Items.Count; i++)
                        {
                            var item = Model.Items[i];
                            <tr>
                                <td>@(i + 1)</td>
                                <td>@item.Name</td>
                                <td>
                                    <a asp-controller="InventoryEquipmentCategories" asp-action="DeleteItem" asp-route-itemId="@item.Id" asp-route-categoryId="@categoryId" class="btn btn-danger btn-sm">Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                }
            </table>
        </div>
    </div>
</div>

OOTTracker/Views/InventoryEquipmentCategories/Index.cshtml
@model OOTTracker.Models.InventoryEquipmentCategories.InventoryEquipmentCategoriesIndexModel
@{
    Layout = "_Layout";
}

<div class="header">
    <h1 class="h4">Inventory Equipment Categories</h1>
    <div class="text-end">
        <a asp-action="Edit" class="btn btn-success">Add Category</a>
    </div>
</div>
<div class="table-responsive">
    <table data-toggle="table" data-pagination="true" data-page-size="10" data-search="true" class="table table-striped table-hover">
        <thead class="table-dark">
            <tr>
                <th data-width="125" scope="col">#</th>
                <th data-width="60" data-width-unit="%" data-field="Name" data-sortable="true" scope="col">Name</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        @if (Model.Categories != null)
        {
            <tbody>
                @for (var i = 0; i < Model.Categories.Count; i++)
                {
                    var category = Model.Categories[i];
                    <tr>
                        <td scope="row">@(i + 1)</td>
                        <td>@category.Name</td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@category.Id" class="btn btn-primary btn-sm me-2">Edit</a>
                            <a asp-action="Delete" asp-route-id="@category.Id" class="btn btn-danger btn-sm">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        }
    </table>
</div>