OOTTracker/Models/Locations/CreateLocationModel.cs
namespace OOTTracker.Models.Locations
{
    public class CreateLocationModel
    {
        public string? Name { get; set; }
    }
}

OOTTracker/Models/Locations/EditLocationFormDataModel.cs
namespace OOTTracker.Models.Locations
{
    public class EditLocationFormDataModel
    {
        public Guid Id { get; set; }
        public string? Name { get; set; }
    }
}

OOTTracker/Models/Locations/EditLocationModel.cs
namespace OOTTracker.Models.Locations
{
    public class EditLocationModel
    {
        public Guid Id { get; set; }
        public string? Name { get; set; }
    }
}

OOTTracker/Models/Locations/EditLocationViewModel.cs
namespace OOTTracker.Models.Locations
{
    public class EditLocationViewModel
    {
        public Guid Id { get; set; }
        public string? Name { get; set; }

        public List<ItemCheckDto>? ItemChecks { get; set; }
    }
}

OOTTracker/Models/Locations/ItemCheckDto.cs
namespace OOTTracker.Models.Locations
{
    public class ItemCheckDto
    {
        public Guid ItemCheckId { get; set; }
        public string? CheckType { get; set; }
        public string? Description { get; set; }
        public string? AgeRequirement { get; set; }
    }
}

OOTTracker/Models/Locations/LocationIndexDto.cs
namespace OOTTracker.Models.Locations
{
    public class LocationIndexDto
    {
        public Guid Id { get; set; }
        public string? Name { get; set; }
    }
}

OOTTracker/Models/Locations/LocationsIndexModel.cs
namespace OOTTracker.Models.Locations
{
    public class LocationsIndexModel
    {
        public List<LocationIndexDto>? Locations { get; set; }
    }
}

OOTTracker/Controllers/ItemChecksController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding.Binders;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OOTTracker.Data;
using OOTTracker.Models.ItemChecks;

namespace OOTTracker.Controllers
{
    public class ItemChecksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ItemChecksController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var _itemChecks = await _context.ItemChecks
                .Include(i => i.Location)
                .Include(i => i.ItemCheckType)
                .Include(i => i.ItemAgeRequirement)
                .ToListAsync();

            var _itemCheckDtos = _itemChecks
                .Select(i => new ItemCheckIndexDto()
                {
                    Id = i.ItemCheckId,
                    Location = i.Location?.Name,
                    Type = i.ItemCheckType?.Name,
                    AgeRequirement = i.ItemAgeRequirement?.Name,
                    Description = i.Description
                })
                .ToList();

            var _model = new ItemChecksIndexModel()
            {
                ItemChecks = _itemCheckDtos
            };

            return View(_model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid? id, Guid? location)
        {
            var _locations = await _context.Locations.ToListAsync();
            var _checkTypes = await _context.ItemCheckTypes.ToListAsync();
            var _ageRequirements = await _context.ItemAgeRequirements.ToListAsync();

            var _locationItems = _locations.Select(l => new SelectListItem()
            {
                Text = l.Name,
                Value = l.LocationId.ToString()
            })
            .ToList();

            var _checkTypeItems = _checkTypes.Select(c => new SelectListItem()
            {
                Text = c.Name,
                Value = c.ItemCheckTypeId.ToString()
            })
            .ToList();

            var _ageRequirementItems = _ageRequirements.Select(a => new SelectListItem()
            {
                Text = a.Name,
                Value = a.ItemAgeRequirementId.ToString()
            })
            .ToList();

            ItemCheckEditViewModel _model;
            if (id == null)
            {
                _model = new ItemCheckEditViewModel()
                {
                    Locations = _locationItems,
                    ItemCheckTypes = _checkTypeItems,
                    ItemAgeRequirements = _ageRequirementItems,
                    LocationId = location
                };

                return View(_model);
            }

            var _itemCheck = await _context.ItemChecks
                .FirstOrDefaultAsync(i => i.ItemCheckId == id);

            if (_itemCheck == null)
                return NotFound();

            _model = new ItemCheckEditViewModel()
            {
                Locations = _locationItems,
                ItemCheckTypes = _checkTypeItems,
                ItemAgeRequirements = _ageRequirementItems,
                LocationId = _itemCheck.LocationId,
                ItemCheckTypeId = _itemCheck.ItemCheckTypeId,
                ItemAgeRequirementId = _itemCheck.ItemAgeRequirementId,
                Description = _itemCheck.Description
            };

            return View(_model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromRoute] Guid? id, [FromQuery] Guid? location, [FromForm] ItemCheckEditFormDataModel model)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            ItemCheck? _itemCheck;
            if (id == null)
            {
                _itemCheck = new ItemCheck();
                await _context.ItemChecks.AddAsync(_itemCheck);
            }
            else
            {
                _itemCheck = await _context.ItemChecks
                    .FirstOrDefaultAsync(i => i.ItemCheckId == id);

                if ( _itemCheck == null) 
                    return NotFound();
            }

            _itemCheck.LocationId = model.LocationId;
            _itemCheck.ItemCheckTypeId = model.ItemCheckTypeId;
            _itemCheck.ItemAgeRequirementId = model.ItemAgeRequirementId;
            _itemCheck.Description = model.Description;

            await _context.SaveChangesAsync();

            //if (TempData["QuickAdd-Redirect"] != null)
            //{
            //    TempData["QuickAdd-ItemCheckId"] = _itemCheck.ItemCheckId;
            //    return RedirectToAction("Edit", TempData["QuickAdd-Redirect"]?.ToString());
            //}

            if (location != null)
                return RedirectToAction("Edit", "Locations", new { id = location.Value });
            
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var _itemCheck = await _context.ItemChecks
                 .FirstOrDefaultAsync(i => i.ItemCheckId == id);

            if (_itemCheck == null)
                return NotFound();

            _context.ItemChecks.Remove(_itemCheck);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }

}

OOTTracker/Controllers/LocationsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OOTTracker.Data;
using OOTTracker.Models.Locations;

namespace OOTTracker.Controllers
{
    public class LocationsController : Controller
    {
        private ApplicationDbContext _context;

        public LocationsController(ApplicationDbContext context) 
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var _locations = await _context.Locations.ToListAsync();
            var _locationDtos = _locations
                .Select(l => new LocationIndexDto() { Id = l.LocationId, Name = l.Name })
                .ToList();

            var _model = new LocationsIndexModel()
            {
                Locations = _locationDtos
            };

            return View(_model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var _model = new CreateLocationModel();


            return View(_model);
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateLocationModel model)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            var _location = new Location()
            {
                Name = model.Name
            };

            await _context.Locations.AddAsync(_location);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var _location = await _context.Locations
                .FirstOrDefaultAsync(l => l.LocationId == id);

            if (_location == null)
                return NotFound();

            var _model = new EditLocationViewModel()
            {
                Id = _location.LocationId,
                Name = _location.Name
            };

            if (id != null)
            {
                ViewData["id"] = id;

                var _itemChecks = await _context.ItemChecks
                    .Where(i => i.LocationId == id)
                    .Include(i => i.ItemCheckType)
                    .Include(i => i.ItemAgeRequirement)
                    .ToListAsync();

                var _itemCheckDtos = _itemChecks.Select(i => new ItemCheckDto()
                {
                    ItemCheckId = i.ItemCheckId,
                    CheckType = i.ItemCheckType?.Name,
                    Description = i.Description,
                    AgeRequirement = i.ItemAgeRequirement?.Name
                })
                .ToList();

                _model.ItemChecks = _itemCheckDtos;
            }

            return View(_model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromRoute] Guid id, [FromForm] EditLocationViewModel model)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var _location = await _context.Locations
                .FirstOrDefaultAsync(l => l.LocationId == id);

            if (_location == null)
                return NotFound();

            _location.Name = model.Name;

            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var _location = await _context.Locations
                .FirstOrDefaultAsync(l => l.LocationId == id);

            if (_location == null)
                return NotFound();

            _context.Locations.Remove(_location);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

    }
}

OOTTracker/Views/Locations/Create.cshtml
@model OOTTracker.Models.Locations.CreateLocationModel
@{
    Layout = "_Layout";
}
<form method="post">
    <div class="row">
        <div class="col mt-2">
            <div class="card">
                <div class="card-header">
                    <h2>Add Location</h2>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-6 mb-3">
                            <label for="Name">Name</label>
                            <input type="text" class="form-control" name="Name" value="@Model.Name" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

OOTTracker/Views/Locations/Edit.cshtml
@model OOTTracker.Models.Locations.EditLocationViewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "_Layout";
}
<form method="post">
    <div class="row">
        <div class="col mt-2">
            <div class="card">
                <div class="card-header">
                    <h2>Edit Location</h2>
                </div>
                <div class="card-body">
                    <ul class="nav nav-tabs" id="navTab" role="tablist">
                        <li class="nav-item" role="presentation">
                            <button class="nav-link active" id="general-info-tab" data-bs-toggle="tab" data-bs-target="#general-info" type="button" role="tab">General Info</button>
                        </li>
                        <li class="nav-item" role="presentation">
                            <button class="nav-link" id="item-checks-tab" data-bs-toggle="tab" data-bs-target="#item-checks" type="button" role="tab">Item Checks</button>
                        </li>
                    </ul>
                    <div class="tab-content" id="navTabContent">
                        <div class="tab-pane fade show active" id="general-info" role="tabpanel">
                            <div class="row">
                                <div class="col-6 mb-3">
                                    <label for="Name">Name</label>
                                    <input type="text" class="form-control" name="Name" value="@Model.Name" />
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="item-checks" role="tabpanel">
                            <div class="row mt-2">
                                <div class="col">
                                    <a class="btn btn-success" asp-controller="ItemChecks" asp-action="Edit" asp-route-location="@ViewData["id"]">Add</a>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <table data-toggle="table" data-pagination="true" data-page-size="10" data-search="true">
                                        <thead>
                                            <tr>
                                                <th data-width="125">#</th>
                                                <th data-field="CheckType" data-sortable="true">Type</th>
                                                <th data-field="Description" data-sortable="true">Description</th>
                                                <th data-field="AgeRequirement" data-sortable="true">Age</th>
                                            </tr>
                                        </thead>
                                        @if (Model.ItemChecks != null)
                                        {
                                            <tbody>
                                                @foreach (var itemCheck in Model.ItemChecks)
                                                {
                                                    <tr>
                                                        <td>
                                                            <a href="/ItemChecks/Edit/@itemCheck.ItemCheckId" class="btn btn-primary me-2">
                                                                <i class="bi-pencil"></i>
                                                            </a>
                                                            <a href="/ItemChecks/Delete/@itemCheck.ItemCheckId" class="btn btn-danger me-2">
                                                                <i class="bi-trash3"></i>
                                                            </a>
                                                        </td>
                                                        <td>@itemCheck.CheckType</td>
                                                        <td>@itemCheck.Description</td>
                                                        <td>@itemCheck.AgeRequirement</td>
                                                    </tr>
                                                }
                                            </tbody>
                                        }
                                    </table>
                                </div>
                            </div>
                          
                        </div>
                    </div>
                  
                    <div class="row">
                        <div class="col">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

OOTTracker/Views/Locations/Index.cshtml
@model OOTTracker.Models.Locations.LocationsIndexModel
@{
    Layout = "_Layout";
}
<h2>Locations</h2>
<div class="row mt-3">
    <div class="col-3">
        <a class="btn btn-primary" href="/Locations/Create">Add Location</a>
    </div>
</div>
<table data-toggle="table" data-pagination="true" data-page-size="10" data-search="true">
    <thead>
        <tr>
            <th data-width="125">#</th>
            <th data-field="Name" data-sortable="true">Location Name</th>
        </tr>
    </thead>
    @if (Model.Locations != null)
    {
        <tbody>
            @foreach (var location in Model.Locations)
            {
                <tr>
                    <td>
                        <a href="/Locations/Edit/@location.Id" class="btn btn-primary me-2">
                            <i class="bi-pencil"></i>
                        </a>
                        <a href="/Locations/Delete/@location.Id" class="btn btn-danger">
                            <i class="bi-trash3"></i>
                        </a>
                    </td>
                    <td>@location.Name</td>
                </tr>
            }
        </tbody>
    }
</table>